spring:
  application:
    name: file-polling-microservice
  datasource:
    url: jdbc:mysql://camel-mysql-srv:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
camel:
  springboot:
    main-run-controller: true
    tracing: true
  component:
    kafka:
      brokers: 'kafka-2.kafka.default.svc.cluster.local:29092,kafka-1.kafka.default.svc.cluster.local:29092,kafka-0.kafka.default.svc.cluster.local:29092'

server:
  port: 8080
